export const images = {
  connected: "/images/connected.png",
  destination: "/images/destination.png",
  downloadBg: "/images/download-bg.png",
  esim: "/images/esim.png",
  handMobile: "/images/hand-mobile.png",
  heroBg: "/images/hero-bg.png",
  heroMobile1: "/images/hero-mobile-1.png",
  heroMobile2: "/images/hero-mobile-2.png",
  house: "/images/house.png",
  logo: "/images/logo.png",
  peoples: "/images/peoples.png",
  plan: "/images/plan.png",
  pyramid: "/images/pyramid.png",
  user1: "/images/user-1.png",
  japan: "/images/japan.png",
  turkey: "/images/turkey.png",
  uk: "/images/uk.png",
  usa: "/images/usa.png",
  germany: "/images/germany.png",
  appStore: "/images/app-store.png",
  googlePlay: "/images/google-play.png",
  world: "/images/world.png",
};
